"""
Wraps OR-Tools calls.
Exposes 2 public methods:
    full_reoptimize()      – triggered by manual buttons / scheduled jobs
    maybe_reoptimize()     – cheap check each tick; does “radar” incremental insertion
"""
from ortools.constraint_solver import routing_enums_pb2, pywrapcp

class OptimizationService:
    def __init__(self, traffic_service): ...
    # ------- manual triggers ---------
    def full_reoptimize(self, trucks, bins): ...
    def collect_all(self, trucks, bins): ...
    # ------- loop hook ---------------
    def maybe_reoptimize(self, trucks): ...
    # ------- helpers -----------------
    def _solve_vrp(self, trucks, candidate_bins): ...
    def _knapsack_filter(self, truck, candidate_bins): ...
